# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f687d80e770a10a743489dd5021cd7d951f139ad48601f1bbc0136c0304e2d35ec54fdf2a604dfed5f6d5628d93cd2ce2603b4db9cef427cac494e29a54655eb

test:
  secret_key_base: e00cf0610873cad16d5f92c688840514bbff72f19c8667a3fa4689d47b0c19bb0dd1178300e74cd54663c3e375083835f41a650ffb1b67ad0dfc439bc8cf7f02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
